/*   Do *not* directly modify this file.  It was    */
/*   generated by the Configuration Tool; any  */
/*   changes risk being overwritten.                */

/* INPUT my_dsp_project.cdb */

/*  Include Header File  */
#include "my_dsp_projectcfg.h"

/*  Config Structures */
/*  Handles  */
